### ISSUE TITLE
Switch stubs throw syntax error "&" unexpected

### ISSUE THREAD

**Issue by ChrisChoke** [paulober/MicroPico#215]
> Please provide a clear and concise description of the bug along with logs

## What are the steps to reproduce this issue?
1. switch stubs to esp32
2.
3.

## What happens?

syntax error

## Any logs, error output, etc?
*(To get extension logs see Terminal > Output > Extension Host and copy output concerning pico-w-go or micropico)*
*(If it’s long, please paste to https://gist.github.com and insert the link here)*

## Any other comments?
i think the "&" sign can be removed?!

https://github.com/paulober/MicroPico/blob/77c6868eb93e2d2fb124f45b78c95f504ecc505e/src/stubs.mts#L292

## Which version of MicroPico are you using?

3.7.5

## Support info

Copy this from the `Help -> Info/About -> Copy` (`Code -> About Visual Studio Code -> Copy` on macOS) option in Visual Studio Code:

```
<paste here>
```

**Comment by wtakuo** [comment]
Hi. 
I ran into the exact same problem last night, and it occurred to me that there might be a problem with the `&` in that line of `stubs.mts`.
I am also using macOS (14.4.1) and VScode version is 1.88.0.
The same problem probably occurs on Linux.
I am not currently using Windows, but I think the `&` at the beginning of the command is probably required by PoweShell. Therefore, instead of simply removing the '&', why not do the following?

```typescript
  const result = execSync(
    (process.platform === "win32" ? "&" : "") +
    `"${pip}" install ${port}==${version} ` + `--target "${target}" --no-user`,
    process.platform === "win32" ? { shell: "powershell" } : {}
  );
```

I would send a pull request for the fix, but for some unknown reason the extension (vsix file) created in the cloned repository doesn't work in my environment. So I'll just leave this comment here.
For the time being, I modified ```~/.vscode/extensions/paulober.pico-w-go-3.7.5-darwin-arm64/dist/extension.cjs``` directly after installing the extension. :-)
