### ISSUE TITLE
No terminal profile provider registered for id "picowgo.vrepl"

### ISSUE THREAD

**Issue by nedamaleki** [paulober/MicroPico#69]
When I need to open Pico (W) vREPL, this error pumps up. I removed and reinstalled both PicoW-Go extension and VSCode and restart my Mac but still gets error.

**Comment by nedamaleki** [comment]
When I need to upload my project to PicoW, this error pumps up. I removed and reinstalled both PicoW-Go extension and Visual Studio and restart my Mac but still gets error.

**Comment by paulober** [comment]
That could be because you have not run "> Pico-W-Go > Connect" command or opened a project with a .picowgo file before to activate the extension and connect to a Pico.  I've currently not registered my extension for activation by the terminal profile. Maybe I find a way to hide it before you connect to a Pico or for a future update an option to use it without a workspace but that would need some more work to be done...

**Comment by paulober** [comment]
@nedamaleki Does the issue with version v3.0.9 still exist?
I tested the extension in Vscode 1.78.2 with Python 3.11 on a new Apple Silicon Mac with macOS 13.4 and had no issues.

**Comment by paulober** [comment]
@nedamaleki Can you confirm that the issue is solved now?
